version: '3.9'

services:
  app:
    image: my-fastapi-app
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
  app2:
    image: my-fastapi-app
    build: .
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8001"
  app3:
    image: my-fastapi-app
    build: .
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8002"